packages:
  - apps/*
  - packages/*

catalogs:
  workspace:
    commitizen: 4.3.1
    cz-git: 1.12.0
    eslint: 9.39.1
    husky: 9.1.7
    lint-staged: 16.2.7
    typescript: 5.9.2
    tsdx: 2.0.0
    bunchee: 6.4.0

  react:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0

  react-native:
    react-native: 0.81.5

  design:
    "@rn-primitives/slot": 1.2.0
    "@tailwindcss/vite": 4.1.18
    class-variance-authority: 0.7.1
    tailwindcss: 4.1.18
    uniwind: 1.2.3

  env:
    "@types/node": 22.15.3

  overrides:
    react-native: "npm:react-native-web@~0.21.0"
    

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
